### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ErriourMe** [World-Control-Team/World-Control#26]
Hi. I have problem with using mod on server. If I'm trying to insert any card to information panel, it makes crash.
Version: WorldControl-1.0.31
Checked cores: Sponge, Mohist (I'm using it more)

```
Description: Ticking block entity

java.lang.AbstractMethodError: worldcontrolteam.worldcontrol.items.ItemFluidCard.getStringData(Ljava/util/List;ILnet/minecraft/item/ItemStack;Z)Ljava/util/List;
	at worldcontrolteam.worldcontrol.api.screen.predefs.ScreenElementProviderCard.onCardUpdate(ScreenElementProviderCard.java:36)
	at worldcontrolteam.worldcontrol.tileentity.TileEntityInfoPanel.func_73660_a(TileEntityInfoPanel.java:484)
	at net.minecraft.world.World.func_72939_s(World.java:2174)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:850)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:924)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:462)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:811)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:663)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Kira076** [comment]
It seems development on the mod is completely dead... But for what it's worth, I actually found the issue... The mod uses .lang files for localisation but minecraft currently expects a .json with the json simply being a mapping from the keys to the localisation... Converter can be found [here](https://tterrag.com/lang2json/) and more info about it can be found [here](https://mcforge.readthedocs.io/en/latest/concepts/internationalization/)... Might submit a pull request later just for posterity?
