### ISSUE TITLE
Inserting Reactor Card crashes when using with IC2 Classic

### ISSUE THREAD

**Issue by SurefireMooly** [World-Control-Team/World-Control#32]
Using WorldControl 1.0.31 with IC2Classic+ 1.12-1.5.4.5.jar, inserting a reactor eu card (generated from right clicking the nuclear reactor in IC2Classic) into the panels crashes the game with this error:

```
Description: Ticking block entity

java.lang.ClassCastException: ic2.core.block.generator.tile.TileEntityNuclearReactorElectric cannot be cast to net.minecraft.inventory.IInventory
	at worldcontrolteam.worldcontrol.crossmod.industrialcraft2.items.IC2ReactorCard.update(IC2ReactorCard.java:36)
	at worldcontrolteam.worldcontrol.tileentity.TileEntityInfoPanel.func_73660_a(TileEntityInfoPanel.java:481)
	at net.minecraft.world.World.func_72939_s(World.java:1838)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)
```

Using the .json fix for a similar crash doesn't change or fix the error

**Comment by dmf444** [comment]
I honestly hate IC2c; these bugs are more annoying than anything. 

I’ll take a look to fix it, thanks for the report.
